### ISSUE TITLE
standardize.default()

### ISSUE THREAD

**Issue by strengejacke** [easystats/datawizard#146]
@mattansb @bwiernik @IndrajeetPatil 

Two points:

1. The default method for `standardize()` is currently located in _effectsize_, however, it passes *all* inputs to `.standardize_models()`. Can we add a check if the input is a model object, and if not, give a warning and return the original input?

``` r
effectsize::standardize(as.complex(1:5))
#> Warning: Could not access model information.
#> Warning: Could not get model data.
#> Error in if (m_info$is_bayesian) {: argument is of length zero
```

2. When _effectsize_ is not loaded, but only _datawizard_, there is no default-method for standardize. This is problematic when applied to a data frame and this data frame contains variables of not-supported classes (like complex) - `standardize()` then fails with error. I'd prefer a message/warning and return the original input instead if it cannot be standardized. Else, we might get errors that are confusing for user. We can't add the default-method to _datawizard_ at the moment, due to a namespace conflict (overwriting). That's why I removed it again from datawizard for that reason:

```r
standardize.default <- function(x, verbose = TRUE, ...) {
  if (isTRUE(verbose)) {
    message(insight::format_message(sprintf("Standardizing currently not possible for variables of class '%s'.", class(x)[1])))
  }
  x
}
```

**Comment by bwiernik** [comment]
Is the long term plan to move the default method to datawizard ?

**Comment by strengejacke** [comment]
Not sure, maybe we need opinions from Indra and Mattan therefore? But Brenton, you had this "dispatch" code for performance and `pp_check()`, can we use that in datawizard, too?

**Comment by DominiqueMakowski** [comment]
> Is the long term plan to move the default method to datawizard ?

it would make sense i think

**Comment by mattansb** [comment]
We have a `standardize.factor` that does nothing, might as well have one for complex and others.

**Comment by mattansb** [comment]
regrouping my thoughts:

1. If we move the default method over, what exactly is `{effectsize}` doing...? That is a code feature of the package.

2. Perhaps there should be an internal method for vectors (used by the data.frame method) that can catch these situations of unsupported vectors?
Would look like this:


```R
standardize.data.frame <- function(...) {
  ...
  
  # Loop through variables and standardize it
  for (var in args$select) {
    x[[var]] <- .standardize_vector(
      x[[var]],
      robust = robust,
      two_sd = two_sd,
      weights = args$weights,
      reference = reference[[var]],
      center = args$center[var],
      scale = args$scale[var],
      verbose = FALSE,
      force = force
    )
  }
  
  ...
}


.standardize_vector <- function(...) {
  UseMethod(.standardize_vector)
}

.standardize_vector.numeric <- standardize.numeric
.standardize_vector.character <- standardize.character
.standardize_vector.factor <- standardize.factor
.standardize_vector.matrix <- standardize.matrix
# etc...

.standardize_vector.default <- function(...) {
  if (isTRUE(verbose)) {
    message(insight::format_message(sprintf("Standardizing currently not possible for variables of class '%s'.", class(x)[1])))
  }
  x
}
```

**Comment by mattansb** [comment]
This is assuming that out main concern here is that when a user passes a data frame, it might contain some unsupported column types.

We can *additionally* add a check in `effectsize::standardize.default` using `insight::is_model()` to then fail if the user passes a truly unsupported model. If effectsize isn't attached, such an attempt would (and should) fail because the user is using a function in wrong way.

So:
- User passes a data frame with an unsupported column - warn.
- User passes an unsupported non-model object - fail.

**Comment by mattansb** [comment]
Oh man, this is actually 1000 times more complicated than what @bwiernik suggested! 😅😅😳

I blame my daughter for not letting me sleep last night!

**Comment by strengejacke** [comment]
> I blame my daughter for not letting me sleep last night!

It'll take some years, but evolution is with you... After 5-10 years w/o sleep you get used to it an be able to think again, even w/o having slept ;-)

**Comment by bwiernik** [comment]
> That is a core feature of the package.

Perhaps historically, but standardize being here also causes issues with performance/effectsize circular dependencies. The more of that functionality that moved to datawizard the better

**Comment by strengejacke** [comment]
But still, if both datawizard and effectsize are loaded, unsupported vector classes should not error, just warn/msg (so you still need to check in effectsize?)

**Comment by strengejacke** [comment]
> The more of that functionality that moved to datawizard the better.

Yeah, that would be the "cleanest" solution, I think.

**Comment by DominiqueMakowski** [comment]
> what exactly is {effectsize} doing...?

Interpreting numbers using random rules of thumb "guidelines" 😁

**Comment by mattansb** [comment]
>Interpreting numbers using random rules of thumb "guidelines" 😁

Yes Dom, we know that's what you want.... :P

---

I don't think the functionality provided by the default method belongs in a package whose stated goal is to "to easily manipulate, clean, transform, and prepare your data for analysis."


> but standardize being here also causes issues with performance/effectsize circular dependencies.

@bwiernik What circular dep with performance?

**Comment by strengejacke** [comment]
> What circular dep with performance?

I guess he meant parameters.

**Comment by strengejacke** [comment]
> Doesn't need to return an error,

It _shouldn't_ return. This is a practical issue I stumbled upon when importing a data set. If you call the data frame method of `standardize()` (or center, or convert_to_na, ...), and there's *1* variable out of 500 that causes an error, it's absolutely annoying. That's why I think it should just return the input and tell the user that it didn't work for one/some/which variables, but it shouldn't stop. Real life data has a lot of garbage, and I don't want to examine each variable carefully to find those I need to leave out/remove.

**Comment by mattansb** [comment]
Yes, then we can make that change.

Moving the function to datawizard will just *add* another circular dependency here 😅
(is datawizard <-> parameters + effectsize <-> parameters better than just effectsize <-> parameters?)

**Comment by DominiqueMakowski** [comment]
*that's why parameters should not used effectsize but the integration of performance, parameters and effectsize should have been done at a higher level **and I will die on that hill***

**Comment by mattansb** [comment]
Totally agree! Isn't that where report is headed?

**Comment by bwiernik** [comment]
Some contraction thoughts:

## parameters and effectsize 

I think the core problem of integration is that effectsize is trying to do too much. It (1) computes all of the supplemental effect sizes people want other than model parameters (cohens d, eta squared, etc), (2) standardize data and model parameters, and (3) do the benchmark interpretation. 

Intuitively, I would expect functionality for standardized model parameters to live in parameters--those are the "parameters" that many folks use exclusively, and that is consistent, eg, with most SEM software having a standardize argument. 

I don't think that the "Compute and work with indices of effect size and standardized parameters" title makes all that much sense, particularly when it causes circular dependency. 

I really think we should move all of that functionality from effectsize to a lower level package, either parameters or datawizard. We can conditionally export the standardize() method from effectsize for backwards compatibility. 

## Home of standardize.default()

Fair enough that the default method might be a little awkward conceptually in datawizard. That said, the method in essence -- runs the data standardize() function then uodate()s the model with the transformed data. The rest of the function is just some safety checking. That doesn't seem to me to be _that_ awkward. 

On a practical level, if the generic lives in datawizard, then the default method really needs to live there too. It is too much of a headache trying to make it work otherwise. We could do something complicated like have a datawizard default method that gives a message to install parameters/effectsize and conditionally export that only if parameters/effectsize size are not available. But why?

A third option would be to remove that functionality from standardize() altogether and instead use a different function like standardize_model(). That function would probably want to live in parameters to resolve the circular dependency. But if the only impetus for this move is conceptual fidelity for datawizard, I'm not sure of the need. 


## report 

This might be a stylistic difference, but a thing I've always liked about R is that it generally gives you only the output you ask for. summary() has always felt a little weird with its wall of mixed together output. 

I really like the easystats/broom approach of separating the different parts of model results into separate functions. That makes it so much easier for me to teach and to focus attention on one part of the modeling process at a time. 

I see value in the demonstration of narrative text in report, and lots of utility for the automatic formatting of in-line statistical text. I can also see use adding functionality for building full model tables that include parameters, performance metrics, etc. ala sjTable(). But I don't know that I see report becoming the one stop shop for new users over the individual packages. It feels more to me like a more advanced package--if you are writing in Markdown, use these functions to get all of your inline R output easily.

**Comment by mattansb** [comment]
All effect sizes available in `effectsize` are also available in `parameters` via a call with the right argument to `model_parameters()` (see [`?model_parameters.htest`](https://easystats.github.io/parameters/reference/model_parameters.htest.html) and [`?model_parameters.aov`](https://easystats.github.io/parameters/reference/model_parameters.aov.html)). So the only way to resolve circular dependency would be to merge (back😅) the packages.

As for `standardize.default()`, `standardize()` is reexported in effectsize from datawizard. Seeing as how we have working solutions, I don't see a *need* to move it, and as a user-facing decision it doesn't seem right :/

But these are just my thoughts, and we can do these moves and merges as you all see fit 🕊️

**Comment by strengejacke** [comment]
> I would expect functionality for standardized model parameters to live in parameters

This was how we had it quite some time ago. However, @DominiqueMakowski and @mattansb - for reasons I can't exactly remember and which I'm sure of I did not agree with 😆 - wanted to have the standardize functions in _effectsize_. I think their argument was that a _standardized_ coefficient is an _effectsize_ because it can be interpreted somehow in terms of Cohen's d.

**Comment by strengejacke** [comment]
Here are some older discussions
https://github.com/easystats/parameters/issues/138
https://github.com/easystats/parameters/issues/142

**Comment by IndrajeetPatil** [comment]
What would it take if we wanted to make _effectsize_ a lower level package than _parameters_?

**Comment by IndrajeetPatil** [comment]
Never mind. Went through _effectsize_ to investigate this, and given that it uses model_parameters internally, this is pretty much impossible.

The only way out would be to go back in time and prevent from this split ever taking place.

**Comment by IndrajeetPatil** [comment]
Yeah, none of those options are ideal. We will just have to live with this circularity.

**Comment by bwiernik** [comment]
I don't have much problem removing effect sizes from parameters

**Comment by strengejacke** [comment]
Yes, effectsizes we have for anova-tables could be removed, but not the feature of standardized coefficients.

Though the docs for _report_ are not very clear, I couldn't figure out how to get different effectsizes, e.g. how to mimic this _parameters_ behaviour?

``` r
library(easystats)
#> # Attaching packages: easystats 0.4.3
#> v insight     0.17.0.2   v datawizard  0.4.0.3 
#> v bayestestR  0.12.0     v performance 0.9.0.1 
#> v parameters  0.17.0.6   v effectsize  0.6.0.7 
#> v modelbased  0.8.0      v correlation 0.8.0.1 
#> v see         0.7.0.1    v report      0.5.1


df <- iris
df$Sepal.Big <- ifelse(df$Sepal.Width >= 3, "Yes", "No")

model <- aov(Sepal.Length ~ Sepal.Big, data = df)
model_parameters(
  model,
  omega_squared = "partial",
  eta_squared = "partial",
  epsilon_squared = "partial"
)
#> For one-way between subjects designs, partial omega squared is equivalent to omega squared.
#> Returning omega squared.
#> For one-way between subjects designs, partial eta squared is equivalent to eta squared.
#> Returning eta squared.
#> For one-way between subjects designs, partial epsilon squared is equivalent to epsilon squared.
#> Returning epsilon squared.
#> Parameter | Sum_Squares |  df | Mean_Square |    F |     p |   Omega2 | Eta2 | Epsilon2
#> ---------------------------------------------------------------------------------------
#> Sepal.Big |        1.10 |   1 |        1.10 | 1.61 | 0.207 | 4.04e-03 | 0.01 | 4.07e-03
#> Residuals |      101.07 | 148 |        0.68 |      |       |          |      |         
#> 
#> Anova Table (Type 1 tests)

report_table(model)
#> For one-way between subjects designs, partial eta squared is equivalent to eta squared.
#> Returning eta squared.
#> Parameter | Sum_Squares |  df | Mean_Square |    F |     p | Eta2 |  Eta2 95% CI
#> --------------------------------------------------------------------------------
#> Sepal.Big |        1.10 |   1 |        1.10 | 1.61 | 0.207 | 0.01 | [0.00, 1.00]
#> Residuals |      101.07 | 148 |        0.68 |      |       |      |
```

<sup>Created on 2022-04-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
For htests, printing could be improved. Some of the columns printed by `report_table()` should better be header/footer:

``` r
library(easystats)
#> # Attaching packages: easystats 0.4.3
#> v insight     0.17.0.2   v datawizard  0.4.0.3 
#> v bayestestR  0.12.0     v performance 0.9.0.1 
#> v parameters  0.17.0.6   v effectsize  0.6.0.7 
#> v modelbased  0.8.0      v correlation 0.8.0.1 
#> v see         0.7.0.1    v report      0.5.1

model <- t.test(mtcars$mpg ~ mtcars$vs)
model_parameters(model, hedges_g = TRUE)
#> Welch Two Sample t-test
#> 
#> Parameter  |     Group | Mean_Group1 | Mean_Group2 | Difference |          95% CI | t(22.72) | Hedges_g |       g 95% CI |      p
#> ---------------------------------------------------------------------------------------------------------------------------------
#> mtcars$mpg | mtcars$vs |       16.62 |       24.56 |      -7.94 | [-11.46, -4.42] |    -4.67 |    -1.64 | [-2.46, -0.79] | < .001
#> 
#> Alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
report_table(model)
#> Parameter  |     Group | Mean_Group1 | Mean_Group2 | Difference |          95% CI | t(22.72) |      p |                  Method | Alternative | Cohen's d |   Cohens_d  CI
#> --------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#> mtcars$mpg | mtcars$vs |       16.62 |       24.56 |      -7.94 | [-11.46, -4.42] |    -4.67 | < .001 | Welch Two Sample t-test |   two.sided |     -1.70 | [-2.55, -0.82]

model <- t.test(iris$Sepal.Width, mu = 1)
model_parameters(model, standardized_d = TRUE)
#> One Sample t-test
#> 
#> Parameter        |   mu | Difference |       95% CI | t(149) | Cohen's d |     d 95% CI |      p
#> ------------------------------------------------------------------------------------------------
#> iris$Sepal.Width | 1.00 |       2.06 | [2.99, 3.13] |  57.81 |      4.72 | [4.17, 5.29] | < .001
#> 
#> Alternative hypothesis: true mean is not equal to 1
report_table(model)
#> Parameter        | Mean |   mu | Difference |       95% CI | t(149) |      p |            Method | Alternative | Cohen's d | Cohens_d  CI
#> -----------------------------------------------------------------------------------------------------------------------------------------
#> iris$Sepal.Width | 3.06 | 1.00 |       2.06 | [2.99, 3.13] |  57.81 | < .001 | One Sample t-test |   two.sided |      4.72 | [4.17, 5.29]
```

<sup>Created on 2022-04-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
Based on what Brenton wrote above, and after looking into the code in _effectsize_, I would suggest:

- Move `standardize.default()` to _datawizard_. This means that the docs have to be revised, to make clear that `standardize()` both works on data _and_ models.
- Move `standardize_parameters()` to _parameters_. Not much needs to be changed here, I think.
- _effectsize_ may re-export these two functions.
- Circular dependency cannot be completely resolved, it's still needed to return effect sizes in _parameters_ (unless we remove that functionality from _parameters_, but I currently see no alternative, because it's not yet fully implemented in _report_).

**Comment by mattansb** [comment]
It seems weird to me to separate between `standardize.default()` and `standardize_parameters()`, especially since this still does not resolve any circular-dependency issues...

But if the tribe has decided so...

**Comment by bwiernik** [comment]
There has to be a default method in the package that expects the generic…
