### ISSUE TITLE
Missing text in pkgdown

### ISSUE THREAD

**Issue by strengejacke** [easystats/datawizard#167]
https://easystats.github.io/datawizard/reference/find_columns.html

![image](https://user-images.githubusercontent.com/26301769/169244199-028cfc7e-f3ae-4991-8624-b98e1379144f.png)

should be

![image](https://user-images.githubusercontent.com/26301769/169244302-76063606-d327-48ed-848a-ec24c870ca69.png)

**Comment by IndrajeetPatil** [comment]
Hmm, looks like another bug introduced in the new version of _roxygen2_? 

Either that or _pkgdown_ doesn't yet work with the new version of _roxygen2_, because I do see this code included in the .Rd files:

https://github.com/easystats/datawizard/blob/3a1ec468077bc0649c183b3e174a3fd9b195063d/man/find_columns.Rd#L140-L144

**Comment by IndrajeetPatil** [comment]
I can confirm that this issue is solved by using  ```r instead of ```.

**Comment by IndrajeetPatil** [comment]
Seems like a bug in _pkgdown_:
https://github.com/r-lib/pkgdown/issues/2092
