### ISSUE TITLE
pivot tests will fail with latest version of poorman

### ISSUE THREAD

**Issue by nathaneastwood** [easystats/datawizard#219]
I think you may need to prepend your tests using the `pivot_*()` functions because the latest version of poorman also contains these functions.

**Comment by IndrajeetPatil** [comment]
I see that these were added by `{easystats}` team member, @etiennebacher!

It's a small world. :)

Thanks for the heads-up, Nathan. I can update `{datawizard}` on CRAN once `{poorman}` is updated. 
You can mention to the CRAN team that the maintainer has been informed, since this will come up in CRAN's revdepcheck.

**Comment by nathaneastwood** [comment]
Ah perfect, the CRAN rev dep check was indeed the one I was worried about. Thanks @IndrajeetPatil!

**Comment by nathaneastwood** [comment]
poorman v0.2.6 is now on CRAN: https://cran.r-project.org/web/packages/poorman/

**Comment by IndrajeetPatil** [comment]
Thanks for letting me know! 

I have already submitted the updated `{datawizard}` to CRAN; currently at the revdepcheck stage. Should be on CRAN soon.
