### ISSUE TITLE
Fix warning in `{easystats}` vignette

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#354]
Ref: https://github.com/easystats/easystats/actions/runs/3946921305/jobs/6755160816

```r
Quitting from lines 32-78 (list_of_functions.Rmd) 
Error:
ℹ In index: 3.
ℹ With name: vignettes/list_of_functions.Rmd.
Caused by error:
! Filtering did not work. Please check the syntax of your `filter`
  argument.
Backtrace:
 1. datawizard::data_filter(all_fns, func %in% fns)
 2. datawizard:::data_filter.data.frame(all_fns, func %in% fns)
 3. insight::format_error("Filtering did not work. Please check the syntax of your `filter` argument.")
 4. insight::format_alert(..., type = "error")
 5. base::stop(...)
```

**Comment by etiennebacher** [comment]
Hum weird. Using `rmarkdown::render("vignettes/list_of_functions.Rmd")` works but `purrr::walk("vignettes/list_of_functions.Rmd", rmarkdown::render)` doesn't

**Comment by etiennebacher** [comment]
Since we use `eval()` in `data_filter()`, my guess is that there's something that messes up with the environment in which the expression is evaluated. 

@IndrajeetPatil I'll try to look more into it, but I think a workaround is to replace `purrr::walk(...)` by `for (i in vignettes ) rmarkdown::render(i)` here:

https://github.com/easystats/workflows/blob/85eb2d49f445afaf9d182e9da528ca0562c79fce/.github/workflows/check-vignette-warnings.yaml#L42

**Comment by IndrajeetPatil** [comment]
See my comment [here](https://github.com/easystats/easystats/issues/348#issuecomment-1396868597). Maybe you can now reproduce the behaviour locally?

**Comment by IndrajeetPatil** [comment]
This should be fixed now (cf. https://github.com/easystats/workflows/issues/29).

**Comment by etiennebacher** [comment]
Thank you, looks good
