### ISSUE TITLE
Rename `add_labs()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#393]
If we agree about renaming, we should try to get this change in the next CRAN update.

Better to make this change ASAP-before users get used to the previous name.

**Comment by IndrajeetPatil** [comment]
@etiennebacher Once this issue is fixed, we are ready for a resubmission.

**Comment by etiennebacher** [comment]
I won't be available this weekend

**Comment by IndrajeetPatil** [comment]
It doesn't need to be this weekend. _Whenever_ the issue is fixed, we will be ready 😅

**Comment by etiennebacher** [comment]
Oops, I thought this was a PR waiting some review so I just wanted to let you know that it wouldn't happen this weekend 😄 

But anyway, I'm fine with renaming but we haven't agreed on a new name. @IndrajeetPatil I think you prefer `apply_labels()`, right? It sounds a bit weird to me because "apply" is more related to functions ("I want to apply this function on this data"). That's why I prefer `assign_labels()` or `give_labels()`, we don't change the data, just add an attribute

**Comment by IndrajeetPatil** [comment]
Good point. I like `assign_labels()` as well!
