### ISSUE TITLE
Unexpected missing values in `data_tabulate()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#514]
There are no missing values in this entire data frame:

``` r
anyNA(mtcars)
#> [1] FALSE
```

And yet it shows up in `data_tabulate()` output:

``` r
datawizard::data_tabulate(mtcars, cyl, gear)
#> cyl (cyl) <numeric>
#> # total N=32 valid N=32
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 4     | 11 | 34.38 |   34.38 |        34.38
#> 6     |  7 | 21.88 |   21.88 |        56.25
#> 8     | 14 | 43.75 |   43.75 |       100.00
#> <NA>  |  0 |  0.00 |    <NA> |         <NA>
```

<sup>Created on 2024-06-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
`datawizard::data_tabulate(mtcars, cyl, gear)` is no valid syntax ;-)


The information in the table is that there are zero `NA` values. If you don't want to include information about missings, set `include_na = FALSE`.

``` r
datawizard::data_tabulate(mtcars, cyl, include_na = FALSE)
#> cyl (cyl) <numeric>
#> # total N=32 valid N=32
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 4     | 11 | 34.38 |   34.38 |        34.38
#> 6     |  7 | 21.88 |   21.88 |        56.25
#> 8     | 14 | 43.75 |   43.75 |       100.00
```

<sup>Created on 2024-06-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by IndrajeetPatil** [comment]
That's an unintuitive UX, IMO. Because I interpreted the `include_na` parameter to mean whether to remove missing values from _data_, not from the _output_. 

Let's see if the users feel the same, and then make the change.

**Comment by etiennebacher** [comment]
> I interpreted the include_na parameter to mean whether to remove missing values from data, not from the output.

Yeah, makes sense to understand this argument like that. We should just remove the line about `NA` if there aren't any. @strengejacke do you agree?

**Comment by strengejacke** [comment]
> We should just remove the line about NA if there aren't any.

In my experience, this would lead to unnecessary double-checks, because you always want to be sure whether there *are* no missing values, or whether they are just *not shown*. When working with data that potentially can have missing values, I think they should be included in the output, even if there aren't any and when they're requested.

We can change the default, and/or rename the argument. But if explicitly requested, I would include even zero-frequencies.

**Comment by strengejacke** [comment]
> Because I interpreted the include_na parameter to mean whether to remove missing values from data, not from the output.

That would be `remove_na` in the easystats-packages.

**Comment by strengejacke** [comment]
(btw, that's why I voted for changing `id_cols` in `by` for `data_to_wide()`, and there's another thread on Twitter (again), where people say that they have to look up the docs each time they use `pivot_wider()`, despite using it for years - the fewer different arguments we have and the more we use a unique name for an "argument that does this task", the better...)

**Comment by strengejacke** [comment]
> `datawizard::data_tabulate(mtcars, cyl, gear)` is no valid syntax ;-)

Correction... If the third argument is `exclude`, it could be valid syntax?

**Comment by etiennebacher** [comment]
> We can change the default, and/or rename the argument. But if explicitly requested, I would include even zero-frequencies.

I'm fine with keeping the current behavior and rename `include_na` to `remove_na` to clarify that it's about the input, not the output. The default behavior wouldn't change since we'd move from `include_na = TRUE` to `remove_na = FALSE`.

> If the third argument is exclude, it could be valid syntax?

It is valid, but useless since `gear` wasn't in the selection anyway.

**Comment by strengejacke** [comment]
Sounds good!

**Comment by strengejacke** [comment]
> to clarify that it's about the input, not the output

Wait, but it's about the output, not the input? Or do our definitions differ here?

**Comment by strengejacke** [comment]
Basically, the difference is that we use `remove_na` in functions that manipulate data, and removing or keeping NA values have an impact on the returned data frame. This affects data _wrangling_ tasks.

We use `include_na` in two functions, `data_tabulate()` and `data_summary()`, both which are data _summarizing_ tasks. And the output may or may not include (i.e.: show) missing values, but it does not affect the function itself (i.e. it will not error).

That's the conceptual difference. And that's why I would say, _if_ we rename `include_na`, we should _not_ rename it into `remove_na` (but rather something like `show_na` or similar).

**Comment by etiennebacher** [comment]
> Wait, but it's about the output, not the input?

`include_na` does affect the computation, i.e it modifies how the input is used internally. It's not just cosmetic:

``` r
library(datawizard)

foo <- mtcars
foo[1, "cyl"] <- NA

data_tabulate(foo, cyl, include_na = TRUE)
#> cyl (cyl) <numeric>
#> # total N=32 valid N=31
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 4     | 11 | 34.38 |   35.48 |        35.48
#> 6     |  6 | 18.75 |   19.35 |        54.84
#> 8     | 14 | 43.75 |   45.16 |       100.00
#> <NA>  |  1 |  3.12 |    <NA> |         <NA>
```

``` r

data_tabulate(foo, cyl, include_na = FALSE)
#> cyl (cyl) <numeric>
#> # total N=31 valid N=31
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 4     | 11 | 35.48 |   35.48 |        35.48
#> 6     |  6 | 19.35 |   19.35 |        54.84
#> 8     | 14 | 45.16 |   45.16 |       100.00
```

<sup>Created on 2024-06-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
> include_na does affect the computation, i.e it modifies how the input is used internally.

I think this applies to literally every existing function. I'd say the more helpful distinction here is what's the purpose of the function. Data wrangling can work as expected or not, depending on whether missing values are included or not. It's something different when you want to summarize your data

**Comment by strengejacke** [comment]
But at second glance, maybe `remove_na` is also ok, if you consider this as "remove all NAs and don't report them" or "don't remove NAs and show how many are actually present in the data". In this line, the upper output makes sense

**Comment by mattansb** [comment]
Just to chime in here - `table()` has a similar `useNA` argument with 3 options: `useNA = c("no", "ifany", "always")`.

Imo, having a similar argument but with the default being `"ifany"` would be best. Like @strengejacke said - it's about summarizing the data.
