### ISSUE TITLE
circular dependencies

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#7]
Note that `adjust` (https://github.com/easystats/datawizard/blob/master/R/adjust.R), `factor_analysis` (https://github.com/easystats/datawizard/blob/master/R/factor_analysis.R), and a few other functions use other `eaystats` packages (mostly `insight` and `model_parameters`).

This is not ideal since we will have another instance of circular dependence. 

Not sure what can we do about this though. Functions used from `insight`, etc., are better off there and should not be moved to `datawinzard` so we will just have to live with this I am guessing 🤷‍♂️

**Comment by strengejacke** [comment]
But only those functions that are affected. The "new" data management functions can be safely moved to datawizard, I guess. But yes, we should prefer to not include circular dependencies here.

**Comment by IndrajeetPatil** [comment]
I will list currently included functions in `datawizard` that have this issue:

1. `adjust`
https://github.com/easystats/datawizard/blob/d757fdc218fa5994e1cf9138c45ff3b85c514c8b/R/adjust.R#L193-L201

2. `center` (this can be solved by also moving `format_message` from `insight` to `datawizard`)
3https://github.com/easystats/datawizard/blob/d757fdc218fa5994e1cf9138c45ff3b85c514c8b/R/center.R#L191-L201

3. `check_clusterstructure`
4https://github.com/easystats/datawizard/blob/d757fdc218fa5994e1cf9138c45ff3b85c514c8b/R/check_clusterstructure.R#L31-L45

4. `demean` (this is easy to solve; just not use color to print the message)
https://github.com/easystats/datawizard/blob/d757fdc218fa5994e1cf9138c45ff3b85c514c8b/R/demean.R#L281-L288

5. `factor_analysis`
https://github.com/easystats/datawizard/blob/d757fdc218fa5994e1cf9138c45ff3b85c514c8b/R/factor_analysis.R#L70-L88

6. `n_factors` (this is easy to solve; just not use color to print the message)
https://github.com/easystats/datawizard/blob/d757fdc218fa5994e1cf9138c45ff3b85c514c8b/R/n_factors.R#L348

7. `reduce_parameters`
https://github.com/easystats/datawizard/blob/d757fdc218fa5994e1cf9138c45ff3b85c514c8b/R/reduce_parameters.R#L146-L153

8. `rescale_weight`  (this can be solved by also moving `format_message` from `insight` to `datawizard`)
https://github.com/easystats/datawizard/blob/d757fdc218fa5994e1cf9138c45ff3b85c514c8b/R/rescale_weights.R#L110

9. `simulate_simpson`
https://github.com/easystats/datawizard/blob/d757fdc218fa5994e1cf9138c45ff3b85c514c8b/R/simulate_simpson.R#L38

**Comment by strengejacke** [comment]
Does insight actually need to depend on datawizard?

**Comment by strengejacke** [comment]
I'd vote for insight still being the package with lowest dependencies. I don't see where insight needs datawizard.

**Comment by IndrajeetPatil** [comment]
Hmm, I thought `datawizard` is going to be the lowest level dependency with all the "helper" functions needed by other packages. But I see no reason why we can't have two such low-level dependencies: 
one-containing data-wrangling related helpers, while the other containing modeling-related helpers.

So, no, `insight` won't need to depend on `datawizard`.

That still leaves open the issue of what to do with `datawizard` functions that rely on `parameters` and `bayestestR`.
Not include them here?

**Comment by DominiqueMakowski** [comment]
Actually, I was about to say that we should also consider moving down some of the essential helpers, like `check_if_installed` (and indeed, following @bwiernik add an argument to check version) and `format_table()`. So that we can use them in datawizard (and regarding the formatting/printing of dataframes, it makes perfect sense to have them in the "data preparing" package). These would be used by insight... 

Conceptually I think the hierarchy is logical and meaningful too: first we start by functions to work with data, then functions to retrieve data from models, then functions to analyze/postprocess specific aspects of models, then functions to report/visualize them. So I'd vote for datawizard as the lowest level (in the long run, tho we could start by having them independent I suppose).
 
The only reasons why we might want to refrain from (that that I can see) are 
1) it might deter other developers from depending on insight if they see that it has a dependency: imo it's always the same story, we just have to explain that all the easystats packages could in fact well be just one package and that they were split for maintenance reasons but there is minimum risk of breakage due to some obscure upstream change (since the stream is actually closed) - which is the main problem with dependencies
2) because insight is such a key foundational stone that you do not want to depend on another package in case it breaks or something. But I'd say that the risk is mitigated since insight would actually depend on only a few robust functions (check_required, format_table and things like that), so I don't see how it can go wrong... And then we have to trust @IndrajeetPatil with his maintaining skills 😋 but so far he's been pretty aware/reactive when it comes to compatibility and stability so 🤷‍♂️ 
3) any other reasons you have in mind?

**Comment by bwiernik** [comment]
Another option if there is a small number of utility functions (like the console coloring, etc.) that both insight and datawizard need, we could use github  submodules to copy them over from insight to datawizard (or vice versa) at build time so that they can exist internally in both, but only be exported by one.

**Comment by bwiernik** [comment]
Where did `simulate_simpson()` come from?

**Comment by DominiqueMakowski** [comment]
correlation

**Comment by DominiqueMakowski** [comment]
> github submodules 

what is this dark magic?

**Comment by bwiernik** [comment]
See https://github.blog/2016-02-01-working-with-submodules/

For example, https://github.com/zotero/zotero here tracks the https://github.com/citation-style-language/styles repository and pulls in the latest versions of its built-in styles at build time.

I think that `simulate_simpson()` could live in either correlation or bayestestR. It's a pedagogical function and I think it reasonable can live with the other correlation analysis functions.

**Comment by IndrajeetPatil** [comment]
> I think that simulate_simpson() could live in either correlation or bayestestR. It's a pedagogical function and I think it reasonable can live with the other correlation analysis functions.

Good point. I think it can continue to stay in `correlation`. Removing it from `datawizard` now.

**Comment by DominiqueMakowski** [comment]
I would prefer to have all the data simulation function together, mostly because it's tidy (besides making sense to be in the data package). I don't see any benefit of having its implementation in correlation it's not like the Simpson's paradox is inherently (or even particularly) related to correlations, we just had it there to illustrate a specific subtype of correlation method, but actually the being able to generate such data could be a useful thing beyond the scope of the correlation package

**Comment by IndrajeetPatil** [comment]
Okay, retaining it then with the other simulate functions.

**Comment by IndrajeetPatil** [comment]
Do you think that `check_clusterstructure` might sit better with other `check_` functions in `performance`, although it's a bird of a different feather?

That'd solve our issue since `performance` already relies on `insight`.

**Comment by DominiqueMakowski** [comment]
conceptually, it makes sense in datawizard, as it's about the structure in dataframe. Now, I'm far from being a stubborn radical idealist, so I'm okay with exceptions due to practical considerations :p

**Comment by IndrajeetPatil** [comment]
haha, okay

But I think the most problematic is this one. `datawizard` can't for sure rely on `parameters`:

https://github.com/easystats/datawizard/blob/d757fdc218fa5994e1cf9138c45ff3b85c514c8b/R/factor_analysis.R#L70-L88

**Comment by strengejacke** [comment]
I think functions like `format_table()` etc. are neither perfectly fitting into _insight_ nor _datawizard_, these would actually require a new formatting package - but we shouldn't add another package for this. So, I still see no needs for insight to depend on datawizard. We should try to build those packages that both are on the lowest level, independent from each other. To do this, we can indeed look at what @bwiernik suggested, importing certain functions like `format_value()` internally in datawizard. Currently, there are 5 packages that rely on insight, which are not from the easystats team. Therefore, I would vote against a) too radical breaking changes in insight, b) adding more package dependencies.

**Comment by IndrajeetPatil** [comment]
In light of all this discussion, I think the most pragmatic solution for now (since we want to get this package on CRAN asap) would be that `datawizard` relies on `insight`, making the latter de facto the lowest level dependency in `easystats`.

**Comment by IndrajeetPatil** [comment]
@DominiqueMakowski I am removing `simulate_` functions from `datawizard` because they require `distributio_*` functions from `bayestestR`.

**Comment by IndrajeetPatil** [comment]
I think these functions should actually be in `bayestestR` and then we can import and re-export them in `correlation` to not cause a breaking change.

**Comment by DominiqueMakowski** [comment]
ok 😞

**Comment by IndrajeetPatil** [comment]
Closing now since the builds are finally passing and we no longer have circular dependency issues.
