### ISSUE TITLE
Add function to replace `NA`s

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/datawizard#72]
We need to avoid collision with [_tidyr_ function](https://tidyr.tidyverse.org/reference/replace_na.html), so need to think of another name than the one used here: https://strengejacke.github.io/sjmisc/reference/replace_na.html

**Comment by strengejacke** [comment]
I'm not sure, I think, it was first in sjmisc,, then tidyr. 8-)

**Comment by etiennebacher** [comment]
I started working on a function for that. So far, I named it `convert_na_to()` (close to `convert_to_na()`, which is already present). I have some doubts about the design of this function, especially with dataframes.

### Should it mimic exactly `tidyr::replace_na()`?

When using with a dataframe, `tidyr::replace_na()` requires specifying the replacement for each column, which means that unspecified columns will keep their `NA`, e.g:
``` r
library(tidyr)

test <- data.frame(
  x = c(1, 2, NA),
  x2 = c(4, 5, NA),
  y = c("a", "b", NA)
)

test %>% 
  replace_na(list(x = 0, y = "missing"))
#>   x x2       y
#> 1 1  4       a
#> 2 2  5       b
#> 3 0 NA missing
```

<sup>Created on 2022-03-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This works in the tidyverse world because one can use `across()` and `where()` to quickly replace all numeric or character values but I don't think they have an equivalent in the easystats world.

Another possibility is not to follow `tidyr::replace_na()` and to have 3 arguments in `convert_na_to()` for numeric, character and factor columns, and to have arguments `select` and `exclude` to know more precisely which variables to modify:
```r
convert_na_to(test, 
              replacement_num = 4, 
              replacement_char = "e",
              replacement_fac = NULL,
              select = "x")

#>   x x2 y
#> 1 1  4 a
#> 2 2  5 b
#> 3 4  NA <NA>
```
What do you think?

**Comment by DominiqueMakowski** [comment]
perhaps `convert_na()`? (we have already several `convert_*` functions even though for a different context)

**Comment by strengejacke** [comment]
Not sure about naming arguments, but I like the suggestion from @etiennebacher 
I would also suggest either that `select` indicate variable names, and the `replace_*` arguments their replacement values, or `select` can be a named list (like in `tidyr::replace_na()`), which would then override / ignore the `replace_*` arguments.
